# start docker kernal + python
FROM python:3.11.9-slim-bullseye
#show logs : python
ENV PYTHONUNBUFFERED=1

# update kernal + install
RUN apt-get update && apt-get -y install gcc libpq-dev

# Folder for my project
WORKDIR /app

# Copy Requirments
COPY requirments.txt /app/requirements.txt

# install requirments
RUN pip install -r /app/requirements.txt

# copy all projects files
COPY . /app/